apiVersion: v1
kind: Service
metadata:
  name: chris-tess-svc
  labels:
    app: christess
spec:
  type: NodePort
  ports:
  - port: 4000
  selector:
    app: christess
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chris-test-dep
  labels:
    app: christess
spec:
  replicas: 1
  selector:
    matchLabels:
      app: christess
  template:
    metadata:
      labels:
        app: christess
    spec:
      containers:
      - name: christess
        image: freelancedeveloper/chris_tess:latest
        ports:
        - containerPort: 4000
